# general
batch_size: 64
input_size: 112
embd_shape: 512
sub_name: 'arc_res50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not
#arc params
margin: 0.15 
logist_scale: 30 
checkpoint_dir: 'Checkpoints/arc_res50/'
# train
#train_dataset: 'data/GLDv2/gldv2_clean.tfrecord'
train_dataset: 'data/GLDv2/gldv2_clean_sample_5k.tfrecord'
binary_img: True
num_classes: 81313
#num_samples: 1580470
num_samples: 5000
num_gpu: 2
epochs: 10
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: 'data/GLDv2/gldv2_clean_sample_5k.tfrecord'
